server:
  port: 8081
spring:
  application:
    name: "rabbit-play-publisher"
  threads:
    virtual:
      enabled: true

management:
  metrics:
    distribution:
      percentiles:
        http.server.requests: "0.5,0.9,0.99"
        http.client.requests: "0.5,0.9,0.99"
        # jvm.gc.pause: "0.5,0.9,0.99"
      percentiles-histogram:
        jvm:
          gc:
            pause: true
      #   http:
      #     server:
      #       requests: true
      minimum-expected-value:
        http:
          server:
            requests: "10us"
        jvm:
          gc:
            pause: "10us"
      maximum-expected-value:
        http:
          server:
            requests: "1ms"
        jvm:
          gc:
            pause: "100ms"
      # slo: 
      # #additional explicit points
      #   http.server.requests: "10ns,100us,5ms"
        
  observations:
    annotations:
      enabled: true
  logging:
    export:
      enabled: false
  otlp:
    metrics:
      export:
        url: http://collector:4318/v1/metrics
        step: 5s
        enabled: false
    tracing:
      endpoint: http://collector:4317/v1/traces
      transport: grpc
      export:
        enabled: false
  tracing:
    sampling:
      probability: 0.1


# logging:
#   level:
#     '[org.springframework]': DEBUG
#debug: true  
